apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  ports:
    - port: 3003
      targetPort: 3003
  selector:
    app: user-service
    tier: user
  type: NodePort
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  selector:
    matchLabels:
      app: user-service
      tier: user
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-service
        tier: user
    spec:
      containers:
      - image: manorfm/user-service
        name: user-service
        env:
        - name: ENV_DATABASE_URL
          value: mongodb
        ports:
        - containerPort: 3003