#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: grafana
#  namespace: monitoring
#spec:
#  selector:
#    matchLabels:
#      k8s-app: grafana
#      name: grafana
#  replicas: 1
#  template:
#    metadata:
#      labels:
#        name: grafana
#        k8s-app: grafana
#    spec:
#      containers:
#      - name: grafana
#        image: grafana/grafana
#        ports:
#        - containerPort: 3000
#          protocol: TCP
#        volumeMounts:
#        - mountPath: /var/lib/grafana
#          name: grafana-storage
#        env:
#        - name: GF_SERVER_HTTP_PORT
#          value: "3000"
#        - name: GF_SECURITY_ADMIN_PASSWORD
#          value: "admin123"
#        - name: GF_INSTALL_PLUGINS
#          value: "grafana-kubernetes-app"
#      volumes:
#      - name: grafana-storage
#---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    name: grafana