apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
  name: prometheus
 name: prometheus
 namespace: monitoring
spec:
  selector:
    matchLabels:
      name: prometheus
  replicas: 1
  template:
   metadata:
    labels:
      name: prometheus
   spec:
    serviceAccountName: prometheus
    containers:
    - name: prometheus
      image: prom/prometheus
      imagePullPolicy: Always
      ports:
        - containerPort: 9090
          protocol: TCP
      volumeMounts:
        - mountPath: "/etc/prometheus"
          name: config-prometheus
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
    volumes:
    - name: config-prometheus
      configMap:
       name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    name: prometheus